name: Build Docker Image

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]
    paths:
      - Dockerfile
      - devhub.sh
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - devhub.sh
  schedule:
    - cron:  '0 5 * * 1'
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push the image after building'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.push_image) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/fonteva/d2x-fork:latest
            ghcr.io/fonteva/d2x-fork:${{ github.sha }}
